server:
  port: ${SERVER_PORT:8080}
security:
  jwt:
    secret: ${JWT_SECRET}
spring:
  application:
    name: "cy_authentication"
  devtools:
    add-properties: false
  r2dbc:
    host: ${SPRING_R2DBC_HOST:localhost}
    port: ${SPRING_R2DBC_PORT:5432}
    database: ${SPRING_R2DBC_DATABASE:cy_auth_db}
    schema: ${SPRING_R2DBC_SCHEMA:public}
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/cy_auth_db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED-ORIGINS:http://localhost:4200,http://localhost:8080,http://localhost:8081}
# logging:
#   level:
#     io.r2dbc.postgresql.QUERY: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  packages-to-scan: co.com.crediya.cy_authentication.api
  webjars:
    prefix: /webjars
