server:
  port: 8080
spring:
  application:
    name: "cy_authentication"
  devtools:
    add-properties: false
  r2dbc:
    host: localhost
    port: 5432
    database: cy_auth_db
    schema: public
    url: r2dbc:postgresql://localhost:5432/cy_auth_db
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"
# logging:
#   level:
#     io.r2dbc.postgresql.QUERY: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  packages-to-scan: co.com.crediya.cy_authentication.api
  webjars:
    prefix: /webjars
